const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s);let current=null, view=null;
const key=()=>crypto.randomUUID();
async function api(path,options={}){const r=await fetch(path,{headers:{"Content-Type":"application/json"},...options});const data=await r.json();if(!r.ok)throw new Error(data.error?.message||"请求失败");return data}
function tell(text,error=false){$("#notice").innerHTML=`<div class="notice ${error?'error':''}">${text}</div>`;setTimeout(()=>$("#notice").replaceChildren(),5000)}
function show(id){$$('.view').forEach(x=>x.classList.toggle('active',x.id===id));if(id==='risks')renderRisks();if(id==='review')renderReview();if(id==='audit')renderAudit()}
$$('[data-view]').forEach(b=>b.onclick=()=>show(b.dataset.view));
async function loadCases(){const d=await api('/api/cases');const picker=$('#case-picker');const rows=d.cases.map(x=>x.case||x);picker.innerHTML='<option value="">请选择</option>'+rows.map(c=>`<option value="${c.caseId}">${c.accessionCode} · ${c.title}</option>`).join('');$('#case-list').innerHTML=rows.length?rows.map(c=>`<div class="card" data-id="${c.caseId}"><span class="tag">${c.status}</span><h3>${c.title}</h3><p>${c.accessionCode}</p><small>版本 ${c.version} · ${c.dyeSensitivity} 敏感</small></div>`).join(''):'<p class="hint">还没有案卷，从建立藏品档案开始。</p>';$$('.card').forEach(c=>c.onclick=()=>selectCase(c.dataset.id));if(current)picker.value=current.case.caseId}
async function selectCase(id){view=await api(`/api/cases/${id}`);current=view;$('#case-picker').value=id;tell(`已选择 ${view.case.title}，当前状态 ${view.case.status}`);show('plan')}
$('#case-picker').onchange=e=>e.target.value&&selectCase(e.target.value);
function obj(form){return Object.fromEntries(new FormData(form))}
$('#case-form').onsubmit=async e=>{e.preventDefault();const x=obj(e.target);x.idempotencyKey=key();x.historicalLuxHours=+x.historicalLuxHours;x.annualLuxHourLimit=+x.annualLuxHourLimit;try{const c=await api('/api/cases',{method:'POST',body:JSON.stringify(x)});await loadCases();await selectCase(c.caseId);tell('藏品档案已建立')}catch(e){tell(e.message,true)}};
$('#add-slot').onclick=()=>{const row=document.createElement('div');row.className='slot-row';row.innerHTML='<input name="slotName" placeholder="时段名称" required><input name="lux" type="number" min="1" placeholder="照度 lux" required><input name="slotMinutes" type="number" min="1" placeholder="分钟" required><button type="button" class="remove-slot" title="删除时段">删除</button>';$('#lighting-slots').append(row);bindSlotButtons()};
function bindSlotButtons(){$$('.remove-slot').forEach(b=>b.onclick=()=>{if($$('.slot-row').length>1)b.parentElement.remove()})}bindSlotButtons();
$('#plan-form').onsubmit=async e=>{e.preventDefault();if(!current)return tell('请先选择案卷',true);const x=obj(e.target);x.idempotencyKey=key();x.expectedVersion=current.case.version;x.lightingSlots=[...$$('.slot-row')].map(r=>({name:r.querySelector('[name=slotName]').value,lux:+r.querySelector('[name=lux]').value,minutes:+r.querySelector('[name=slotMinutes]').value}));delete x.slotName;delete x.lux;delete x.slotMinutes;x.dailyOpenMinutes=+x.dailyOpenMinutes;x.restRotationDays=+x.restRotationDays;x.uvProtection=e.target.uvProtection.checked;try{const r=await api(`/api/cases/${current.case.caseId}/plans`,{method:'POST',body:JSON.stringify(x)});$('#assessment').innerHTML=`<div class="result"><h3>测算结果</h3><div class="metric">${r.assessment.projectedLuxHours} lux·h</div><p>峰值 ${r.assessment.peakLux} lux · 年度余量 ${r.assessment.annualRemainingLuxHours} lux·h · 安全裕度 ${r.assessment.safetyMarginPercent}%</p><p>生成 ${r.findings.length} 项风险发现</p></div>`;await selectCase(current.case.caseId);tell('方案修订与计算快照已保存')}catch(e){tell(e.message,true)}};
async function renderRisks(){if(!current)return $('#risk-list').innerHTML='<p>请先选择案卷。</p>';current=await api(`/api/cases/${current.case.caseId}`);const a=current.assessments.at(-1);const fs=current.findings.filter(f=>f.assessmentId===a?.assessmentId);$('#risk-list').innerHTML=fs.length?fs.map(f=>`<div class="finding ${f.severity}"><span class="tag">${f.severity} · ${f.status}</span><h3>${f.summary}</h3><p>${f.evidenceRequirement}</p>${f.status==='open'?`<form data-finding="${f.findingId}" class="grid"><label>整改措施<input name="resolutionNote" required></label><label>佐证说明<input name="evidence" required></label><label>登记人<input name="actor" value="designer-b" required></label><button>登记闭环</button></form>`:`<p>整改：${f.resolutionNote}<br>佐证：${f.evidence}</p>`}</div>`).join(''):'<div class="result">当前测算未发现风险，可以送交专业复核。</div>';$$('[data-finding]').forEach(f=>f.onsubmit=resolveRisk)}
async function resolveRisk(e){e.preventDefault();const x=obj(e.target);x.idempotencyKey=key();x.expectedVersion=current.case.version;try{await api(`/api/cases/${current.case.caseId}/risks/${e.target.dataset.finding}/resolve`,{method:'POST',body:JSON.stringify(x)});current=await api(`/api/cases/${current.case.caseId}`);renderRisks();tell('风险整改已登记；如涉及参数，请创建新方案修订重新测算')}catch(e){tell(e.message,true)}}
async function renderReview(){if(!current)return $('#review-evidence').innerHTML='<p>请先选择案卷。</p>';current=await api(`/api/cases/${current.case.caseId}`);const a=current.assessments.at(-1),r=current.revisions.at(-1);$('#review-evidence').innerHTML=`<div class="result"><span class="tag">${current.case.status}</span><h3>${current.case.title}</h3><p>方案修订 ${r?.revisionNumber||'-'} · 预计剂量 ${a?.projectedLuxHours||'-'} lux·h · 证据事件 ${current.audit.length} 条</p><p>申请人：${current.case.createdBy}（复核人必须为其他人员）</p></div>`}
$('#submit-review').onclick=async()=>{if(!current)return tell('请先选择案卷',true);try{await api(`/api/cases/${current.case.caseId}/submit-review`,{method:'POST',body:JSON.stringify({idempotencyKey:key(),expectedVersion:current.case.version,actor:'protector-a'})});await renderReview();tell('案卷已送交专业复核')}catch(e){tell(e.message,true)}};
$('#review-form').onsubmit=async e=>{e.preventDefault();if(!current)return tell('请先选择案卷',true);const x=obj(e.target);x.idempotencyKey=key();x.expectedVersion=current.case.version;x.validDays=+x.validDays;try{const r=await api(`/api/cases/${current.case.caseId}/review`,{method:'POST',body:JSON.stringify(x)});current=await api(`/api/cases/${current.case.caseId}`);$('#permit-result').innerHTML=r.permit?`<div class="result"><h3>已签发展陈凭据</h3><div class="metric">${r.permit.verificationCode}</div><p>有效期 ${r.permit.validFrom.slice(0,10)} 至 ${r.permit.validUntil.slice(0,10)}</p></div>`:'<div class="result">案卷已退回整改。</div>';tell('复核决定已保存')}catch(e){tell(e.message,true)}};
$('#verify-form').onsubmit=async e=>{e.preventDefault();try{const r=await api('/api/permits/verify?code='+encodeURIComponent(e.target.code.value));$('#verification').innerHTML=`<div class="result"><h3>${r.valid?'凭据有效':'凭据无效'}</h3><p>状态：${r.status}</p><p>${(r.conditions||[]).join('；')}</p><small>证据摘要 ${r.evidenceDigest||'-'}</small></div>`}catch(e){tell(e.message,true)}};
async function renderAudit(){if(!current)return $('#timeline').innerHTML='<li>请先选择案卷。</li>';const r=await api(`/api/cases/${current.case.caseId}/audit`);$('#timeline').innerHTML=r.audit.map(a=>`<li><strong>#${a.Sequence} ${a.EventType}</strong><br><span>${a.Actor} · ${new Date(a.OccurredAt).toLocaleString()}</span></li>`).join('')}
api('/api/ready').then(()=>{$('#health').textContent='服务就绪';$('#health').classList.add('ok');loadCases()}).catch(e=>tell(e.message,true));
